const ERROR_CODES = Object.freeze({
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  STORAGE_CONFIG_UNAVAILABLE: 'STORAGE_CONFIG_UNAVAILABLE',
  GUEST_QUOTA_UNAVAILABLE: 'GUEST_QUOTA_UNAVAILABLE',
  GUEST_UPLOAD_REJECTED: 'GUEST_UPLOAD_REJECTED',
});

module.exports = { ERROR_CODES };
